plugins {
    id "com.android.application"
}

android {
    namespace "com.ameprobe.flexshizuku"
    compileSdk 37

    defaultConfig {
        applicationId "com.ameprobe.flexshizuku"
        minSdk 31
        targetSdk 37
        versionCode 1
        versionName "1.0.0"
    }

    buildFeatures { aidl true }
}

dependencies {
    implementation "dev.rikka.shizuku:api:13.1.5"
    implementation "dev.rikka.shizuku:provider:13.1.5"
}
